package com.patc.enums;

public enum Type {
    NORMAL, FIRE, WATER, GRASS, ELECTRIC, BUG,
    FLYING, FIGHTING, GHOST, DARK, PSYCHIC, POISON,
    GROUND, ROCK, STEEL, DRAGON, FAIRY, ICE, NONE
}